name: corona_lineage_dynamics
channels:
  - conda-forge
  - defaults
dependencies:
  - boost
  - boost-cpp
  - c-compiler
  - curl
  - cxx-compiler
  - make
  - r-base
  - r-mass
  - r-matrix
  - pkg-config
