name: corona_lineage_dynamics
channels:
  - conda-forge
dependencies:
  - boost
  - boost-cpp
  - curl
  - make 
  - pkg-config 
  - r-base 
  - r-binom
  - r-countrycode
  - r-d3heatmap
  - r-devtools
  - r-doparallel
  - r-dplyr
  - r-foreach
  - r-htmltools
  - r-htmlwidgets
  - r-knitr
  - r-lifecycle
  - r-mass
  - r-matrix
  - r-pkgdown 
  - r-plotly
  - r-plyr
  - r-ragg
  - r-rcpp
  - r-rcurl
  - r-readr
  - r-scales
  - r-stringr
  - r-systemfonts 
  - r-tictoc
  - r-tidyr
  - r-withr
  - r-xml
  - r-xml2 
  - r-xtable
  - zlib 
  - cxx-compiler
  - c-compiler
