name: Update Lineage List

on:
  schedule:
    - cron: '0 3 * * *'  # runs daily at 03:00 UTC
  workflow_dispatch:      # allows manual triggering

jobs:
  update-lineage-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download latest lineage_list.html
        run: |
          curl -sSL https://cov-lineages.org/lineage_list.html -o testdata/lineage_list.html

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add testdata/lineage_list.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update lineage_list.html from cov-lineages.org"
          git push

